name: Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - 'website/**'
      - 'data/**'


jobs:
  render-data:
    name: Render Data
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup and render
        run: |
          make setup-ci
          make render

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: FabrizioCafolla
          author_email: developer@fabriziocafolla.com
          message: 'feat(release): Update README.md'
          add: 'README.md website/src/data/outputs.json'
          tag_push: '--force'

  deploy:
    name: Deploy Github pages
    runs-on: ubuntu-20.04
    needs: render-data
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build